Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.serverless.app.audioconversion.handlers.SNSHandler
      CodeUri: C:\Users\Hp\IdeaProjects\converttoaudio
      Runtime: java8